version: "3.9"

services:
  postgres:
    container_name: postgres14
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: voyager_db
    volumes:
      - /data/postgres
    ports:
      - 54321:5432
  # app:
  #   depends_on:
  #     - postgres
