CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar NOT NULL,
  "email" varchar NOT NULL UNIQUE,
  "password" varchar NOT NULL,
  "role" varchar NOT NULL DEFAULT 'regular',
  "created_at" timestamp NOT NULL DEFAULT (now())
);
